### ISSUE TITLE
How to npm install and run the application front end and java

### ISSUE THREAD

**Issue by rihabesx** [aboudard/springboot-module-federation#1]
Could you please describe how to run this demo application frontend and java spring part.

I am trying to npm install the ng-shell application but getting the following error:

❯ npm i                                                                                                                                                                          ─╯
npm ERR! code ETARGET
npm ERR! notarget No matching version found for core@15.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
 
It can not find core@15.0.0 package.

**Comment by aboudard** [comment]
Hello, thank you for your message ! 
Indeed that's because you have to publish or install the shared library that I called `core`, but as I look at the repo, I see that I didn't include it in this repo.
Basically, it's this one here :
https://github.com/aboudard/angular-module-federation/tree/main/projects/core

I'm sorry, I should have checked.

**Comment by rihabesx** [comment]
Thank you so much for your prompt response.

I will try this tonight and see how it goes.

I was also wondering how you generated the project sturture that has both
java/spring and angular in the same repo?

Also how would this be packaged to be deployed on tomcat?

Appreciate your response as I am trying to do something similar since we
are use both Java and angular.

Regards,
Salim

**Comment by aboudard** [comment]
Well, for the generation, this project is really standard, so you start with a Spring Boot "starter" maven project (or graddle if you want) and simply run a `ng new` command inside a dedicated folder of your maven project.
The good thing is, if you have some CI/CD, you can tell to a maven action to run a npm script, and make your pipeline simple.

Anyway, feel free to drop a message if the instructions are not clear in the readme, I'd be happy to check with you.

Cheers
Alain

**Comment by rihabesx** [comment]
thank you so much for your prompt response.

I managed to build and run the application and it works!

So in this setup if you need to introduce another mfe module does it need
to be part of the application? Or it can be developed and deployed
separately and then at run time it's manifest is fetched and it's loaded
dynamically?

Regards,
Salim

**Comment by aboudard** [comment]
In this setup, the mfe apps are exposed via a unique `manifest` endoint.
Then this endpoint is fetched here :
https://github.com/aboudard/springboot-module-federation/blob/master/application/ng-shell/src/main.ts

This means that in this version, you need to add any new manifest to this endpoint in order to load a new mfe.
This is done in the Java module of the mfe, by implementing the proper interface (notice that some values are hard coded, like the URL, but it could be dynamic) :

https://github.com/aboudard/springboot-module-federation/blob/master/library/src/main/java/com/cit/mfe1/Mfe1ManifestProvider.java

But the thing is, you could have any other mfe hosted anywhere else, and all you should do, is add some code in the main Angular app to declare those new mfe's.

I'm planning on writing an article, but I'm very happy to give you more details if you need.

PS: I'm very glad that it does work now, thank you again for the feedback !

**Comment by rihabesx** [comment]
Hello Alain!

Thanks again for your great support as a fellow developer.

Please see below my comments under your email notes as my remarks to show
my understanding and also my question below regarding the deployment of the
multiple java providers and components.


Basically, what I am trying to do is a shell application with certain
common functionality that will have the capability to load widgets and
other components remotely. I would like to have the development and
deployment cycles of the main shell application and the remote mfe(s)
separated since different teams will be working on either. I am just
wondering how close is your concept to this use case?
Appreciate your feedback and thanks again.

regards,
Salim.

On Sun, 28 Apr 2024 at 15:33, Alain Boudard ***@***.***>
wrote:

> In this setup, the mfe apps are exposed via a unique manifest endoint.
> Then this endpoint is fetched here :
>
> https://github.com/aboudard/springboot-module-federation/blob/master/application/ng-shell/src/main.ts
>
*this is clear how it fetches all the manifests under this uri
/manifest/all*


> This means that in this version, you need to add any new manifest to this
> endpoint in order to load a new mfe.
> This is done in the Java module of the mfe, by implementing the proper
> interface (notice that some values are hard coded, like the URL, but it
> could be dynamic) :
>
*What I understand is that the java module will implement the manifest
provider and spring will scan for all the endpoints, however, what I
envision is that the shell application (frontend and backend) to be
agnostic of any new mfe(s) deployed and loaded in the future. So the
question is how will the java part be deployed? Does the java part of the
new mfe need to be deployed as part of the main shell application?*

>
> https://github.com/aboudard/springboot-module-federation/blob/master/library/src/main/java/com/cit/mfe1/Mfe1ManifestProvider.java
>
> But the thing is, you could have any other mfe hosted anywhere else, and
> all you should do, is add some code in the main Angular app to declare
> those new mfe's.
>
*Can you please elaborate more on this, may this has the answer to my
remark above. *

**Comment by aboudard** [comment]
Alright, thanks for your questions.

I don't really see how completely agnostic your app and mfe's could be, since, for example, you probably would like them to speak to each other, like I do with the NgRx Store in this example.

My experiment states that the core backend is Java, so if I understand your question, I should always package my mfe's inside a Java module, as I show in the video, the target would be a standalone .jar that would be integrated to an existing app afterwards. 
The main app is built separately from any mfe in my vision, so that would fit your description, a separated team could work on any part of the project.

- You build the main app (front and back) : team 1
- You build any number of mfe (front and back) : team 2, 3, 4
- You build one or more shared libraries (front and back) : team 5, 6
- You simply add the .jar of every mfe to the classpath of your main app, and retstart the server

Note that in this experiment, I placed all the code in a single `pom.xml` :
https://github.com/aboudard/springboot-module-federation/blob/master/pom.xml

But this is only for demo purpose, you could separate all the components and import them as maven dependencies in IDE (for core) or as .jar (for mfe) on the server, the possibilities are multiple.

Now, about the possibility to load another mfe that would not fit this structure, You would simply need to add custom code, just like in this version (angular only) of the POC :
https://github.com/aboudard/angular-module-federation/blob/main/projects/shell2/src/app/app.component.ts

As long as you control where the list of your mfe's is managed, you're good.

If I were you, I would take this POC and explode the main `pom.xml` in separate projects, and then reconcile them the way I described.

Hope this helps.
Alain

**Comment by rihabesx** [comment]
Hi,
Please see my comments below.

regards,
Salim

On Mon, 29 Apr 2024 at 11:49, Alain Boudard ***@***.***>
wrote:

> Alright, thanks for your questions.
>
> I don't really see how completely agnostic your app and mfe's could be,
> since, for example, you probably would like them to speak to each other,
> like I do with the NgRx Store in this example.
>
*I meant to explain that the shell application development and deployment
is independent to any deployment of future mfe's, but for sure, the mfe's
will be built on opinionated conventions so that they can either message
the shell application or message any other mfe's through some interface
implementation.*

> My experiment states that the core backend is Java, so if I understand
> your question, I should always package my mfe's inside a Java module, as I
> show in the video, the target would be a standalone .jar that would be
> integrated to an existing app afterwards.
> The main app is built separately from any mfe in my vision, so that would
> fit your description, a separated team could work on any part of the
> project.
>
*Does the mfe jar need to be added to main app and server restart is
required? *

>
>    - You build the main app (front and back) : team 1
>    - You build any number of mfe (front and back) : team 2, 3, 4
>    - You build one or more shared libraries (front and back) : team 5, 6
>    - You simply add the .jar of every mfe to the classpath of your main
>    app, and retstart the server
>
> Note that in this experiment, I placed all the code in a single pom.xml :
>
> https://github.com/aboudard/springboot-module-federation/blob/master/pom.xml
>
 you like this ?














*<?xml version="1.0" encoding="UTF-8"?><project
xmlns="http://maven.apache.org/POM/4.0.0
<http://maven.apache.org/POM/4.0.0>"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance
<http://www.w3.org/2001/XMLSchema-instance>"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
<http://maven.apache.org/POM/4.0.0>
https://maven.apache.org/xsd/maven-4.0.0.xsd
<https://maven.apache.org/xsd/maven-4.0.0.xsd>">
<modelVersion>4.0.0</modelVersion>
<groupId>org.springframework</groupId>
<artifactId>module-federation</artifactId>
<version>0.0.1-SNAPSHOT</version>    <packaging>pom</packaging>
<modules>        <module>library</module>    </modules></project>*

*and another project for application and another for core?*


But this is only for demo purpose, you could separate all the components
> and import them as maven dependencies in IDE (for core) or as .jar (for
> mfe) on the server, the possibilities are multiple.
>
> Now, about the possibility to load another mfe that would not fit this
> structure, You would simply need to add custom code, just like in this
> version (angular only) of the POC :
>
> https://github.com/aboudard/angular-module-federation/blob/main/projects/shell2/src/app/app.component.ts
>
> *so in this case, the call to get manifest/all at bootstrap is not being
used (or it could be used to capture manifests bundles within the current
application state), and then in addition some how there will need to be
another call to get all other independent mfe's that were deployed later
and on different domains to load them? Is my understanding correct? or you
can only use one way or the other at bootstrap time or above link?*

> As long as you control where the list of your mfe's is managed, you're
> good.
>
> If I were you, I would take this POC and explode the main pom.xml in
> separate projects, and then reconcile them the way I described.
>
>
*Also, I have been experimenting with the Nx framework and their
implementation of mfe, I noticed that you are using
angular-architects/module-federation, are there any
similarities/differences. Can your code be ported to Nx? I have not see
manifest setup in Nx or may be I missed it. *
*Appreciate your feedback.*

**Comment by aboudard** [comment]
> Does the mfe jar need to be added to main app and server restart is required? 

Yes, in this POC, yes. Again, the whole point of this is to provide an app that can run multiple mfe's in the same process, because we want to deliver a single application for a client. If you don't need that and you can run as many mfe's as you want in separate HTTP servers.

> and another project for application and another for core?

Yes, that would be something like that if we want to separate the maven projects.

> Can your code be ported to Nx? I have not see manifest setup in Nx or may be I missed it.

This POC depends on the library from angular-architects, Nx has its own implementation, but it doesn't adress my issue that was to embed a mfe in a maven library. The point of a Nx project is to have a monorepo, with multiple apps, that eventually, shell and mfe's, will be hosted separately. If we wanted to port my project to Nx, we would have multiple Nx projects, one in each Maven module, that would not resemble at all that kind of structure :
https://github.com/nrwl/ng-module-federation/tree/main/apps

Again, the main goal of my POC is to host all apps in the same web context of a single Spring Boot server, if you don't have that kind of need, you really can go with Nx, which actually make the same job, meaning module federation.

Cheers
